#!/bin/bash
set -e -x

# Installing basic tools
apt-get update -qq
apt-get install -qq -y curl git jq unzip

# Downloading chefdk
curl -sSlo /resources/chefdk.deb \
  https://packages.chef.io/files/stable/chefdk/${CHEFDK_VERSION}/ubuntu/16.04/chefdk_${CHEFDK_VERSION}-1_amd64.deb

# Installing chefdk
dpkg -i /resources/chefdk.deb

# Installing capistrano gems for deployments
chef exec gem install --no-document capistrano-rails capistrano-rbenv capistrano-chef capistrano-deploytags

# Installing AWS-CLI
echo "Download/Install AWS-CLI and jq..."
if [ ! "$(aws --version 2>/dev/null)" ]; then
  curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  cd /tmp && unzip -q awscliv2.zip && ./aws/install && rm awscliv2.zip && cd -
fi

# CIS Hardening
sed -i -e "s/^PASS_MAX_DAYS\s\+99999/PASS_MAX_DAYS   60/" /etc/login.defs
sed -i -e "s/^PASS_MIN_DAYS\s\+0/PASS_MIN_DAYS	7/" /etc/login.defs
sed -i -e "s/^UMASK\s\+022/UMASK	027/" /etc/login.defs

# Cleaning
apt-get clean
rm -rf /tmp/*